### ISSUE TITLE
[SuMo] Zygarde formes

### ISSUE THREAD

**Issue by Snowysauce** [LegendaryPKMN/ivcalc#15]
The species drop-down list currently has four entries for Zygarde: 10% forme, 50% forme, Complete forme, and a default entry for Zygarde. The default entry is the same as the 50% forme, since that was Zygarde's only forme in Generation 6.

The default and 50% forme entries should be merged. Also, note that the 50% forme entry has a base Sp. Defense of 80, while the default entry has a base Sp. Defense of 95. The latter number is the correct base Sp. Defense for 50% forme Zygarde.

**Comment by Arty2** [comment]
Pushed a quickfix for this, in https://github.com/LegendaryPKMN/ivcalc/commit/c0f7a0863c965cc945f868f841541c70dfdaf666 but will have to change the dataset properly in the future.
