### ISSUE TITLE
Alolan Diglett's Special Defense Stat

### ISSUE THREAD

**Issue by Spydrouge** [LegendaryPKMN/ivcalc#25]
Something appears to be wrong with Alolan Diglett's Special Defense Stat on the ivCalculator. I'm using the latest version, and it wants the special defense stat of numerous bred, traded, and wild caught alolan diglet to be about 10 units higher than it actually is. 

If you need an example, here's a level 22 I just pokepelago-ed to EV train, but which is otherwise untouched:
Jolly, Alert to Sounds:
HP 40 Attack 49 Defense 19 Special Attack 24 Special Defense 31, Speed 71, 
With 252 EVs invested in Attack, and 252 EVs invested in Speed.

The Iv Calculator is positive the Special Defense needs to be 40-47. 

If you need more examples, I have a few.

**Comment by 2007heaven** [comment]
Hey there @Spydrouge.

Thanks for taking the time to submit an issue. Examples of how to reproduce this with other inputs would indeed help!

**Comment by Snowysauce** [comment]
@Spydrouge 

Thanks for the report. The base Special Defense for Alolan Diglett was set to 80 instead of the correct value of 45. It has been fixed as part of #27.
