### ISSUE TITLE
Zygarde Sp. Def

### ISSUE THREAD

**Issue by Titobaube** [LegendaryPKMN/ivcalc#26]
Hello,
In the IV calcuator, Zygarde (50% form) base Sp.Def is listed as 80, while it is actually 95. Realized something was wrong when it told me my Zygarde had a stat 15 points above what was possible.

**Comment by Arty2** [comment]
Thank you kindly for your feedback. What forme have you noticed the issue
with? It would be very helpful if you could provide a SaveCode for this
Pokemon: click on *Save* and copy/paste the results in the status field.

͞ı̵І͞І

**Comment by Arty2** [comment]
Thank you kindly for your feedback. What forme have you noticed the issue with? It would be very helpful if you could provide a SaveCode for this Pokemon: click on *Save* and copy/paste the results in the status field.

**Comment by Titobaube** [comment]
?sc=0,0,1,0,! ,,,,,,! 718.2,50,183,120,137,89,115,115,0,0,0,0,0,0,1,0.1,6,3,5.1.0,-1


Was using this one https://www.serebii.net/games/iv-calcsm.shtml,
 but just realized the error was fixed on yours https://legendarypkmn.github.io/ivcalcsm.html

Don't mind my useless comment then...
<https://legendarypkmn.github.io/ivcalcsm.html>
Sun & Moon Individual Value & Stat Calculator ...<https://legendarypkmn.github.io/ivcalcsm.html>
legendarypkmn.github.io
This IV Calculator / Stat Calculator / Hidden Power Calculator aims to help Pokemon trainers calculate the attributes of their Pokemon.



Serebii.net Games - Individual Value Calculator<https://www.serebii.net/games/iv-calcsm.shtml>
www.serebii.net
Team mode: Useful for IV Battles; use this to calculate multiple Pokémon at once. For an IV Battle, gather a team of low level Pokémon and battle with a friend online, forcing them to level 100, then writing down their projected stats.




________________________________

**Comment by Arty2** [comment]
Not useless at all, I shall let Joe know to update the Serebii version as well.
Thanks again for pointing this.
