### ISSUE TITLE
Diancie/Hoopa/Volcanion

### ISSUE THREAD

**Issue by Snowysauce** [LegendaryPKMN/ivcalc#3]
In the Pokémon species dropdown list, Diancie's name is misspelled as "Diance". (This is referring to the standard entry for Diancie; the Mega Evolution entry is spelled correctly.)

Also, the Pokédex numbers for Hoopa (standard entry) and Volcanion are reversed in the dropdown list's code. Volcanion is listed as #720, and Hoopa is listed as #721. #720 should be Hoopa; #721 should be Volcanion. Although the calculator works fine for both Pokémon, the error causes the wrong sprite to show when either Pokémon is selected.

**Comment by Arty2** [comment]
Thanks! Will fix as soon as possible : )

**Comment by Snowysauce** [comment]
I fixed the Diancie typo as part of my pull request for issue #4. I didn't edit Hoopa or Volcanion since that change also requires edits to the compressed Pokémon stat data.

**Comment by Arty2** [comment]
Excellent, thank you, will merge asap :)

**Comment by Snowysauce** [comment]
Resolved
