### ISSUE TITLE
Selection of best stats doesn't work

### ISSUE THREAD

**Issue by BrysonWoods** [LegendaryPKMN/ivcalc#30]
on a tablet using three best stat categories makes it not work and on computer i cant even choose one

**Comment by Arty2** [comment]
Thanks for reporting this @BrysonWoods.
What browser are you using on the computer (eg Chrome, Safari, Firefox) and what happens when you click on the Best Stats dropdown?

This particular field needs to be redesigned into multiple checkboxes as it doesn't seem to work well on touch devices.

**Comment by Arty2** [comment]
Could not investigate, ticked closed.
