### ISSUE TITLE
Espeon IVs too high?

### ISSUE THREAD

**Issue by miniman1125** [LegendaryPKMN/ivcalc#31]
I have an Espeon that I wanted to check the IV’s for. All of the other stats were fine except the Speed stat. It says, “Speed (62) should be 53 to 60.” It shows 62 on my 3DS. I was wondering if the Pokémon having pokérus before is a factor of this?
![AAD2DA7D-5F1E-4AAF-AF11-E95DADC24C15](https://user-images.githubusercontent.com/51772477/59403261-f30b4880-8d6f-11e9-9781-de9d7c7b4a2f.jpeg)
![98C7AFAC-3796-4A08-B7F2-E73E5213D0CB](https://user-images.githubusercontent.com/51772477/59403262-f30b4880-8d6f-11e9-8a56-69a7afb31b7f.jpeg)

Please let me know if something is wrong.

**Comment by miniman1125** [comment]
I’ve also only used one vitamin on the Espeon, that being a calcium, but that raises Sp.A.

**Comment by Snowysauce** [comment]
@miniman1125 I notice in your second screenshot that your Espeon's experience points bar is not empty, which leads me to believe that the Pokémon has battled either wild Pokémon or a trainer's Pokémon. Either way, Espeon would have gained EVs/EPs from those battles, and it's highly likely that your Espeon's EVs are not empty, especially in Speed.

You can check the relative EV levels of your Pokémon by pressing Y at the above screens. The blue hexagon will change to a yellow hexagon with adjacent areas for each stat that are either dark yellow (if your Pokémon's EVs are not maxed out) or blue (if they are). These areas loosely represent how many EVs your Pokémon has for a specific stat. Again, my guess is that not only does Espeon have the 10 Sp. Attack EVs from the Calcium, your Espeon also has a lot of EVs in Speed.

If you do not know the exact number of EVs your Pokémon has in each stat, no IV calculator anywhere will return valid results.

**Comment by miniman1125** [comment]
Ok thanks I only picked sun up a while ago and it was apparently a used game with this Espeon already in a box. So the other owner must have put some carbos on it. Thanks for the help!
