### ISSUE TITLE
Unlabelled box

### ISSUE THREAD

**Issue by CrisHale** [LegendaryPKMN/ivcalc#38]
A minor issue, and possibly to do with the website serebii.net rather than this tool - I'm not sure - but on [this page](https://www.serebii.net/games/iv-calcswsh.shtml) there's an unlabelled box to the right of the Characteristic box. It has some Pokémon types in it, but not all.
Edit: Also, there are some IV figures in bold, but the help text doesn't say why.

**Comment by Arty2** [comment]
Thanks for reporting this @CrisHale, I shall let Joe know. This is a remnant of Hidden Power being determined by the IVs in previous games and thus assisting in the reverse calculation. 

Regarding the IV figures in bold, they're just the median values, but not an indicator of how likely they are. Media values are used by default in the active fields of the right side, which you can use to calculate the stats, or —only in previous games— the Hidden Power type and strength.
