### ISSUE TITLE
Diancie don't appear

### ISSUE THREAD

**Issue by jaizor11** [LegendaryPKMN/ivcalc#39]
Diancie don't appear in the list of pokemon selectables

**Comment by Arty2** [comment]
Diane is *unobtainable* in Sword & Shield (as of writing this at least) hence it is not supposed to appear in the “Sword & Shield Individual Value & Stat Calculator” which I assume you are using. The calculator for Sun & Moon is available here: https://legendarypkmn.github.io/ivcalcsm.html
