### ISSUE TITLE
Reversion of changes

### ISSUE THREAD

**Issue by Snowysauce** [LegendaryPKMN/ivcalc#7]
The latest revision to the XY calculator undid all of the fixes I submitted earlier. Thus, issue #4 is a bug once again, issue #3 is completely unresolved, and several typos and errors were reintroduced.

**Comment by Arty2** [comment]
Thank you for the hawk-eyed attention; I really appreciate it!

I will take care of these two during the weekend, but it would be very helpful if you could point out the typos.

**Comment by Snowysauce** [comment]
Resolved
