### ISSUE TITLE
Can't select Best Stats

### ISSUE THREAD

**Issue by Alkaris** [LegendaryPKMN/ivcalc#8]
I think someone done goofed on the selection drop down for Best Stats because the options listed aren't clickable when I click on the dropdown list for Best Stats for HP, Attack, Defence, Sp. Attack, Sp. Defence, and Speed.

**Comment by kootoopas** [comment]
Hey @Alkaris.

Its functionality is a little bit weird. In order to select multiple stats you need to hold `ctrl` or `cmd` and click. It also doesn't point out which ones you've clicked. Sounds like a nice enhancement if someone fixed its UX, to me. 🤔 

Which browser/os are you using?

**Comment by Alkaris** [comment]
I'm using Chrome Version 55.0.2883.75 (64-bit) on Linux Mint 18 (Cinnamon) 64-bit.

it's just weird it's not selecting anything while it's acting as multiselect thing with a dropdown menu.
